### ISSUE TITLE
Lenovo Tab4 10 Plus (Android 7.0.1) - first transfer incomplete

### ISSUE THREAD

**Issue by Ryder17z** [machinateur/android-chrome-tab-transfer#11]
No error message.

Transfer halted with a success message without copying all tabs.

Any retries seems to work fine.

**Comment by machinateur** [comment]
That's extremely difficult to reproduce without knowing the PHP version, or having the device on hand.

This might be related to some sort of connection delay (if something like that exists; it's just a guess at this point).

There were several other issues concerning the connectivity. In response to that I've updated the download logic. It now uses curl instead of a php native function and reports more verbosely about what's actually happening.

> To run the command with debug verbosity, append `-vvv` to the end of the command:
>
> php copy-tabs.php -vvv

That way, possible errors with the download, as well as the download process and steps themselves, will be printed to the console.

If you can still reproduce this issue, please try to do so with the newest version ([v0.4.0](https://github.com/machinateur/android-chrome-tab-transfer/releases/tag/0.4.0)).

**Comment by ExileFox** [comment]
not possible to test as the device stopped working when I dropped it. I think the issue can be closed.
