### ISSUE TITLE
Adb detect bug

### ISSUE THREAD

**Issue by zDot-sr** [machinateur/android-chrome-tab-transfer#12]
If computer having 2 or more adb.exe file founded, cmd will return "The adb executable is not available!"
Tested by deleting the rest of the adb files.
![image](https://user-images.githubusercontent.com/57571112/189112532-e1cd21ad-2640-4a87-97ea-1b9f7bbc4e23.png)

**Comment by machinateur** [comment]
The reason this is failing seems to be that under windows the command used to check the `adb` availability (`where`) returns all matching paths.

See:
- [`where`](https://ss64.com/nt/where.html)
- [`command` (linux/mac)](https://man7.org/linux/man-pages/man1/command.1p.html)

I'll change the way this is done. The command output should be split at `\n` and then reduced to a `bool` using the logic already in place (plus file extension check on windows, as it's looking for a pattern instead of a match I guess).
