### ISSUE TITLE
Suggestion: File write - `output` directory & timestamp

### ISSUE THREAD

**Issue by wedebe** [machinateur/android-chrome-tab-transfer#30]
To keep user data separate from working code, could I suggest writing to a dedicated `output` folder?

Also, there's currently ya risk of dataloss when the script is re-run, as previous output files are blindly overwritten...
to mitigate this, I think timestamps would be worthwhile.

Eg.
```
./tabs.json
./tabs-reopen.sh
./tabs-gist.md
```

Would become
```
./output/tabs-2024-08-20-1900.json
./output/tabs-reopen-2024-08-20-1900.sh
./output/tabs-gist-2024-08-20-1900.md
```

(I've tried running `php copy-tabs.php -- outputfile`, but get a red-boxed error: `Command "outputfile" is not defined.`

**Comment by machinateur** [comment]
Based on the error you received, this is due to the argv parsing getting confused here.

Technically the command is a standalon symfony console application, with `copy-tabs` as default command. My suspicion would be that the `--` messes up the parsing somehow.

Since the output file is actually an optional positional argument, it should work with the following command: `php ./copy-tabs.php tabs-of-2024.json`. This would write the following files:

```
./output/tabs-of-2024.json
./output/tabs-of-2024-reopen.sh
./output/tabs-of-2024-gist.md
```

---

But to get back to your question regarding adding a timestamp feature and putting the output into a separate directory:

As of now this is a technical limitation of the implementation. Initially I wanted to "protect" inexperienced users by simply only taking the filename from the output file argument.

I can definitely see the advantages of being able to re-request the tabs regularly without the need of taking care of naming to not overwrite the files from the last execution.

**Comment by machinateur** [comment]
New version `0.4.5` contains a flag to control the addition of a timestamp to the filename, which is active by default.
